### ISSUE TITLE
Prevent all extensions from loading Bootstrap

### ISSUE THREAD

**Issue by LarryTX** [kartik-v/yii2-krajee-base#103]
How can I prevent all Kartik-V extensions from loading Bootstrap 4 after my custom Bootstrap 4 is already loaded? I have a customized version of Bootstrap 4 that is loaded in my layout and, hence, available at all times. I've tried disabling every reference to Bootstrap in yii2-krajee-base. Nonetheless, every time I turn around, I find that my colors for info, sucess, etc. are being totally ignored, my fonts are being ignored, my font-size has become much too small, etc. Then I look at the page source and find some thing like:
```php
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="/assets/ff8a18c1/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/7510eb36/css/dropdown.css" rel="stylesheet">
    <link href="/assets/ad0646c0/css/kv-grid.css" rel="stylesheet">
    <link href="/assets/be60ac47/css/bootstrap-dialog-bs3.css" rel="stylesheet">
    <link href="/assets/ad0646c0/css/jquery.resizableColumns.css" rel="stylesheet">
    <link href="/assets/ad0646c0/css/perfect-scrollbar.css" rel="stylesheet">
    <script src="/assets/be60ac47/js/dialog.js"></script>
```
Thus, every bit of presentation that I have worked hard to create is overridden. Surely there is some easy way to prevent this from happening. I don't mind the extension-specific css, plugin css and js and so. But why do I have to have my Bootstrap css overridden? Why is Bootstrap reloaded when it is already loaded?

**Comment by kartik-v** [comment]
@LarryTX I suppose this was answered somewhere else. 

You need to use Yii2's asset management features to load and override your own CSS and JS - instead of directly loading these CSS/JS files in your view layout or view file via `link` or `script` tags as you are doing.

You need to go through the Yii2 Asset Management guide. For example, [this section in the guide mentions how you can load your own custom JQuery](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#customizing-asset-bundles). 

You can do the same to override the Bootstrap CSS/JS and any other custom extension bundles as well.

**Comment by LarryTX** [comment]
As always, Kartik is so very helpful, telling us how to do something that we already know. Since the goal is to override the injection of Bootstrap by his extensions, that means that we have to go through every single extension of his attempting to find everywhere he injects some contorted, personally customized Bootstrap. How convenient. Kartik is truly an ambassador for every other framework. A true guiding force to drive people away from Yii.

**Comment by LarryTX** [comment]
My CSS an JS is already combined and compressed and loaded through Yii2 Asset Management. The issue is how to prevent it from being overridden by the Kartik extensions. I will just post this question elsewhere.

**Comment by kartik-v** [comment]
Since you know already how to use Yii2 Framework to do this - am not then engaging in a discussion here. I am sure one can use Yii2 Framework's asset manager to override CSS/JS from all asset bundles (including assets / CSS/JS from other extensions). Not a right way to get help and hence I am deleting your offending comment.
