### ISSUE TITLE
Workaround PJAX fix for weird back / forward browser button behavior 

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-krajee-base#59]
When rendering jQuery plugins in PJAX container - the plugins behave weirdly when browser back/forward buttons are pressed. The plugins render duplicate content OR tend to break in back/forward navigations.

With this fix the back/forward button presses on browser will reload the page - thereby making the jquery plugins initialize correctly.

**Comment by lieszkol** [comment]
This fix - specifically the following line in WidgetTrait.php - is breaking my site:

$view->registerJs("window.addEventListener('popstate',function(){window.location.reload();});");

I use manual ajax loads independently of the kartik grid. Unfortunately the above line ends up reloading the whole page after any successful ajax loads. Took me 2 hours to pin down the culprit.

**Comment by kartik-v** [comment]
The fix will only be applicable when browser back and forward buttons are pressed and when pjaxContainer is set within widgets.

**Comment by kartik-v** [comment]
Refer enh # 60... you can set `enablePopStateFix` property for your widget to `false` to prevent the above fix from executing.

**Comment by lieszkol** [comment]
Thanks so much!!! And also thank you SO MUCH for all the work you put into your components...I don't get how it's all worth it for you but I'm very happy for it.

**Comment by lieszkol** [comment]
I would argue that injecting this line into the generated page: 
`window.addEventListener('popstate',function(){window.location.reload();});`
is inherently a bad idea because popstate can be triggered by other events than the user pressing the back button (such as my example below). Additionally, a full page reload on a modern one-page website is worse than losing some small functionality (like, for example, a Kartik widget not properly reinitalizing after an ajax load). The latter is a small bug that can be easily identified and rectified by a developer, while a full-page reload coming from a short bit of js injected into an ajax response is very difficult to track down. 
My suggestion would be not to enable this hack by default. However, if the pros of having this bug-prone workaround really outweigh the cons, then it would be good to highlight this in the docs:

- Make a note of this setting in [editable docs](http://demos.krajee.com/editable), somewhere around this section: "pjaxContainerId: string, the identifier for the PJAX widget container if the editable..."
- Also make a note in [editable-column docs](http://demos.krajee.com/grid#editable-column) where EditableColumn is described
- Do a console.log(... right before the page reload, to make the life of devs easier by giving them an indication of what is causing the page reload

What brought me here again? _Two years later and this bit me once again - this time when using EditableColumn in a GridView inside of a bootstrap dialog loaded using jquery .load() (with pjaxContainerId set on the editable so that it correctly reinitializes whenever the gridview is refreshed). I was triggering the opening of a bootstrap dialog from an `<a href="#" onClick="...">` menu item, and forgot to "`return false`" from the onClick handler. Because of this small oversight Chrome was triggering a popstate event whenever I used the menu item to open the dialog. After the gridview was loaded once this way, the code in question would be injected, and the next time I would click on the menu item the whole page would refresh because of the "hack" implemented in this issue._ 

Thanks again for all of the work you and the other core team members have put into making YII the best PHP framework out there. Long live YII!
