### ISSUE TITLE
Refactor code and consolidate / optimize properties within traits

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-krajee-base#94]

**Comment by Bhoft** [comment]
if you have the parameters e.g. `_isBs4` inside the trait you have to remove them in the using classes.
Otherwise you will get issues there.

e.g. 
`
 PHP Strict Warning – yii\base\ErrorException
 kartik\form\ActiveForm and kartik\base\BootstrapTrait define the same property ($_defaultIconPrefix) in the composition of kartik\form\ActiveForm. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed...
`
But I guess you are still on it as some extensions have this values in the class directly ;)

**Comment by kartik-v** [comment]
@Bhoft thanks - these have been already taken care of collectively across all extensions probably at the same time you were commenting 😄 .

**Comment by kartik-v** [comment]
Fixed via #95 - thanks.

**Comment by vbazovic** [comment]
I think this is the same problem: kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($_msgCat) in the composition of kartik\export\ExportMenu. However, the definition differs and is considered incompatible. Class was composed

**Comment by kartik-v** [comment]
@vbazovic  ensure you have the latest stable releases of all extensions with dependencies by running composer update (in your case yii2-export and its dependencies)

The [updated code for ExportMenu](https://github.com/kartik-v/yii2-export/blob/master/src/ExportMenu.php) does define the properties correctly based on trait definition.

**Comment by vbazovic** [comment]
My first step was composer update and cahce cleanup, and the error is after this. But for some reason when I looked, after your reply, in vendor folder there was an old version (1.2.8). What is strange is than on the other machine everything was OK. With identical composer.json. So after some try-error cycles I found out that the problem was mising php-gd library which then forced phpoffice/phpspreedshet to fall back to phpoffice/phpexcel which then downgraded your library to 1.2.8 if you use "@dev", as per your documentation for installing your fantastic library. So what worked for me:
`sudo apt-get install php-gd`
`composer remove kartik-v/yii2-export`
`composer clearcache`
`composer install kartik-v/yii2-exportq1q`

Perhaps you can omit "@dev" in documentation?

**Comment by danabyrd** [comment]
Thanks for your wonderful work Mr Kartik. My project has 25 composer references to yii2-krajee-base within the vendors folder of my project. The yii2-krajee-base version references are listed below with a count for each (these counts are a sum of krajee-base references in the vendor folders.
`>=2.0.0 (9 counts)
>=1.9   (9 counts)
>=1.9.8 (1 count)
*       (6 counts)`
**Can anyone suggest how I should go about resolving my dependency issues?** 
My plan is to start with the 1.9 entries, change one composer entry at a time, run composer update and see what happens. The issue appears to be arising from composer.json files in the vendor sub-folders, and not the primary project level composer.json file.

**Comment by kartik-v** [comment]
You may want to start by reading about PHP Composer package manager to understand what you should be doing and 

You are not supposed to be changing any code or files or JSON configs in the `vendor` folders. These are part of the vendor packages that will be automatically parsed and overwritten by composer

The purpose of using composer package manager is to avoid doing any tinkering of the source codes of vendors. You just need to manage all of your composer dependencies within Yii2 via the application root's composer.json.
